FROM ubuntu:16.04

ARG USERNAME
ARG PASSWORD

ENV LANG ja_JP.UTF-8
ENV LC_CTYPE ja_JP.UTF-8

RUN apt-get update -y \
	&& apt-get install -y curl git sudo build-essential locales python \
    && curl -sL https://deb.nodesource.com/setup_8.x | bash - \
    && apt-get install -y nodejs \
	&& apt-get clean \
	&& rm -fr /var/lib/apt/lists/* \
    && locale-gen ja_JP.UTF-8 \
    && localedef -f UTF-8 -i ja_JP ja_JP.utf8

RUN git clone https://github.com/c9/core.git /root/cloud9 \
    && cd /root/cloud9 \
    && ./scripts/install-sdk.sh

COPY docker-entrypoint1.sh /

WORKDIR /root/workspace

ENTRYPOINT ["/docker-entrypoint1.sh"]
